### ISSUE TITLE
As a user, I want to enter my credentials so that I can login to the dashboard

### ISSUE THREAD

**Issue by waiyan13** [KMD-Group-2/ideas-poll-ui#1]
## Acceptance Criteria

Feature: Authentication

    Scenario: When the user navigates to website
        Given the user has correct credentials
        When the user logs in
        Then the user is redirected to dashboard

    Scenario: When the user navigates to website
        Given the user has incorrect credentials
        When the user logs in
        Then the user is prompted with login status
## Tasks List

- [ ] Design login UI
- [ ] Implement form validation
- [ ] Implement request/response parsing
- [ ] Implement error handling

## Resources

- [Figma Designs](https://www.figma.com/file/y5spFdArxR0D4Ptcl6u2gR/EWSD-Project?t=YkbMYyaqepjvxkUM-1)
- [Material UI](https://mui.com/)
